defaults: &defaults
  #working_directory: ./circleci
  docker:
    - image: circleci/node:8

version: 2
jobs:
  prepare:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build
  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm run test
  deploy-github:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install deployment dependencies
          command: |
              npm install -g --silent gh-pages
              git config --global user.email "$GH_EMAIL"
              git config --global user.name "$GH_NAME"
      - run:
          name: Deploy
          command: |
              gh-pages -d build
workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - prepare:
          filters:
            branches:
              only:
                - master
      - build:
          requires:
            - prepare
      - test:
          requires:
            - build
      - deploy-github:
          requires:
            - test